# Build a binary with dynamically linked
FROM gcc:12 AS builder
COPY . /usr/src/hello/
WORKDIR /usr/src/hello
RUN gcc hello.c -o hello

FROM scratch
COPY --from=builder /lib/x86_64-linux-gnu/ /lib/x86_64-linux-gnu/
COPY --from=builder /lib64/ /lib64/
COPY --from=builder /usr/src/hello/hello /hello
CMD ["/hello"]